using System;using System.IO;using System.Text.Json.Nodes;using Emberfall;using UnityEngine;
public static class EconomyGrowthTests
{
 static int n;static void Check(bool ok,string why){n++;if(!ok)throw new Exception(why);}static string State(ProgressionService p)=>JsonUtility.ToJson(p.Profile,true);
 public static string Run(string root){n=0;
  foreach(int level in new[]{29,30,34,35,40,49,50,64,65,79,80,94,95,100}){int expected=level<30?0:level<35?5:level<50?10:level<65?15:level<80?20:level<95?30:35;Check(ProgressionService.MasteryCap(level)==expected,"exact mastery cap boundary");
   var p=new ProgressionService(Path.Combine(root,"cap"+level));p.NewGame(HeroClass.Arcanist);p.Profile.level=level;p.Save();Check(string.IsNullOrEmpty(p.LastError),"save level");for(int i=0;i<expected;i++)Check(p.LearnMastery(MasteryType.Technique),"legal allocation");Check(!p.LearnMastery(MasteryType.Technique),"cap rejects another point");Check(p.Load()&&p.Profile.masteryRanks[3]==expected,"save normalization preserves legal investment");Check(p.SaveBuildPreset(0,true)&&p.ResetMastery(true)&&p.ApplyBuildPreset(0,true)&&p.Profile.masteryRanks[3]==expected,"build preset roundtrip shares level cap");if(expected>=10)Check(p.SelectMasteryCore(MasteryType.Technique,true)&&p.MasteryCoreTier(MasteryType.Technique)==(expected>=20?2:1),"one core keeps10/20 thresholds");
  }
  foreach(int level in new[]{30,35,40,49,100}){var p=new ProgressionService(Path.Combine(root,"legacy"+level));p.NewGame(HeroClass.Vanguard);p.Profile.level=level;p.Save();var json=JsonNode.Parse(File.ReadAllText(p.SaveFilePath));int rank=ProgressionService.MasteryCap(level);json["profile"]["masteryRanks"]=new JsonArray(rank,0,0);json["profile"].AsObject().Remove("masteryRevision");File.WriteAllText(p.SaveFilePath,json.ToJsonString());Check(p.Load()&&p.Profile.masteryRanks[0]==rank,"legacy revision retains legal ranks");Check(p.Profile.skillPoints+rank==level-1,"legacy points neither minted nor destroyed");}
  Check(ProgressionService.ReforgeGoldCost(10,11)==42&&ProgressionService.ReforgeGoldCost(10,20)==510&&ProgressionService.ReforgeGoldCost(20,50)==2730&&ProgressionService.ReforgeGoldCost(10,50)==3240,"fixed requested quotes");
  for(int a=1;a<99;a++)for(int b=a+1;b<100;b++){int c=100;Check(ProgressionService.ReforgeGoldCost(a,b)+ProgressionService.ReforgeGoldCost(b,c)==ProgressionService.ReforgeGoldCost(a,c),"split pricing path independent");}
  var service=new ProgressionService(Path.Combine(root,"reforge"));service.NewGame(HeroClass.Arcanist);service.Profile.level=10;service.Profile.gold=9999;service.Profile.mechanicMaterials=24;service.Save();var item=service.CreateMechanicItem(EquipmentMechanic.FrostEcho);item.mechanicVariantUnlocked=true;item.mechanicVariant=1;Check(service.CollectLoot(item)&&service.Equip(item.id),"obtain stable item");service.Profile.level=20;service.Profile.slotUpgradeRanks[2]=4;service.Save();var quote=service.QuoteReforge(item.id);Check(quote.FromLevel==10&&quote.TargetLevel==20&&quote.GoldCost==510,"immutable initial quote");
  service.Profile.level=50;service.Save();string before=State(service),disk=File.ReadAllText(service.SaveFilePath);int events=0;service.Changed+=()=>events++;Directory.CreateDirectory(service.SaveFilePath+".tmp");Check(!service.ReforgeMechanic(quote,true)&&State(service)==before&&events==0&&File.ReadAllText(service.SaveFilePath)==disk,"save failure preserves full profile disk and events");Directory.Delete(service.SaveFilePath+".tmp");int gold=service.Profile.gold;Check(service.ReforgeMechanic(quote,true)&&service.Profile.gold==gold-510&&service.Profile.mechanicMaterials==24,"quote charges gold once no fragments");var updated=service.Equipped(ItemSlot.Relic);Check(updated.id==item.id&&updated.level==20&&updated.upgradeLevel==4&&updated.mechanic==item.mechanic&&updated.rarity==item.rarity&&updated.locked&&updated.mechanicVariantUnlocked&&updated.mechanicVariant==1,"fixed target and item identity rarity mechanic upgrade lock preserved");before=State(service);Check(!service.ReforgeMechanic(quote,true)&&State(service)==before,"stale quote cannot charge again");
  service.Profile.gold=1;service.Save();quote=service.QuoteReforge(item.id);before=State(service);Check(!service.ReforgeMechanic(quote,true)&&State(service)==before&&service.Profile.mechanicMaterials==24,"fragments cannot pay missing gold");
  return "PASS: "+n+" economy quote, migration, cap and atomicity assertions";
 }
}
